### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by SomaSekimoto** [SomaSekimoto/chat-space#9]
# IPアドレス
18.176.131.168

**Comment by kohei-isoda** [comment]
関本さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◯ インクリメンタルサーチが機能していない

◯ ユーザー編集画面にある左右ボタンの文字色が違う（白に統一でお願いします！）
[![Screenshot from Gyazo](https://gyazo.com/a75ce4680d22e365368e551f5d063016/raw)](https://gyazo.com/a75ce4680d22e365368e551f5d063016)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by SomaSekimoto** [comment]
インクリメンタルサーチが機能していないということですが、具体的にどの部分でしょうか？グループ作成・編集機能は正常に動作しているのですが。。

**Comment by miyu-yamamoto** [comment]
再提出ありがとうございます！
前回の修正を依頼した箇所は問題なく実装できていました✨
今回新たに修正箇所がありますので再度確認をお願いします。

**○  画面を縮小表示するとフッダー部分が崩れてしまう**
[![Image from Gyazo](https://i.gyazo.com/28b75ccc1846132b45672654e9fea48d.gif)](https://gyazo.com/28b75ccc1846132b45672654e9fea48d)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
